package com.bmilab.backend.domain.file.enums;

public enum FileDomainType {
    PROJECT,
    TIMELINE,
    REPORT,
    BOARD,
    BOARD_IMAGE,
    TASK,
    TASK_RFP,
    TASK_ANNOUNCEMENT,
    TASK_FINAL_PROPOSAL,
    TASK_FINAL_SUBMISSION,
    TASK_PROPOSAL_RELATED,
    TASK_PROPOSAL_MEETING_NOTES,
    TASK_STRUCTURE_DIAGRAM,
    TASK_FINAL_PRESENTATION,
    TASK_DRAFT_PRESENTATION,
    TASK_AGREEMENT_FINAL_PROPOSAL,
    TASK_AGREEMENT_FINAL_SUBMISSION,
    TEMP
}
